roman:
  children:
    roman-prod:
      hosts:
        127.0.0.1
      vars:
        ansible_connection: local
        notebook_instance_type: r5.xlarge
        notebook_min_capacity: 1
        notebook_max_capacity: 10
        notebook_desired_capacity: 1
